version: '3.9'

services:
  eureka-app:
    container_name: eureka_app
    image: stp:eureka
    build: .
    ports:
      - "8761:8761"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-app:8761/eureka