server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: usuarios
          uri: http://localhost:8090
          predicates:
            - Path=/api/usuario/**
        - id: oauth
          uri: http://localhost:8120
          predicates:
            - Path=/iniciar-sesion
            - Path=/registrarse
            - Path=/cerrar-sesion
            - Path=/refrescar-token